### PR TITLE
Add convenience functions of read/decode RGBA8.

### PR DESCRIPTION
**Pull request by TomMD**
Sorry for the noise on the patch, I ran dos2unix thinking my editor was in an
odd mode and didn't realize the whole file was in dos form, hence my editor
leaving the awkward newlines.

### CODE REVIEW

**Comment by Twinside** [comment]
I think this pull request will push me to implement the total version of it with a preferable

    convertRGBA8 :: DynamicImage -> Either String (Image PixelRGBA8)

type. And maybe with `convertRGB8`

**Comment by TomMD** [comment]
Sounds great, streak my `converRGBA8'`.

**Comment by Twinside** [comment]
I will :)

**Comment by TomMD** [comment]
Awesome commit, much better and more complete than this pull.  Thanks!

**Pull request closed without merging**
