### PR TITLE
Support for decoding RGBA8 (32-bit) BMPs

### PR DESCRIPTION
**Pull request by mtolly**
Pretty straightforward. Pixels are in BGRA order, with no line padding since the length is always a multiple of 4.

It appears encoding (`instance BmpEncodable PixelRGBA8`) is already supported.

### CODE REVIEW

**Comment by Twinside** [comment]
This would be perfect with a small 32bits BMP as a test image :]

**Comment by mtolly** [comment]
I haven't forgotten about this; I'm just having trouble getting an appropriate test image. All the tools I've tried make compressed BMPs (even ImageMagick with `convert foo.png -compress none foo.bmp`), which results in the error `Bitmap Can't handle BMP file (32,1,3)`. The images I actually needed this for are a bit large and also don't actually use the alpha channel.

**Comment by Twinside** [comment]
According to [the MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183376%28v=vs.85%29.aspx) this would be normal for a 32bits RGBA, it's not compressed it just looks like a weird flag. I just have to be more forgiving in the input I guess, your input file should be ok.

**Comment by mtolly** [comment]
Sounds good. I've updated the commit to accept either 0 or 3, and added a test image.

**Comment by Twinside** [comment]
Perfect!

**Comment by mtolly** [comment]
Ah, I forgot to update documentation (the main `README.md`, and the documentation for `Codec.Picture.Bitmap.decodeBitmap`). Do you want another PR for those or will you update those?

**Comment by Twinside** [comment]
Don't bother, I have to make a round of updates to the changelog/README.md/else before making a release. I'll do it this week-end as there is already enough content and bugfixes.

**Comment by Twinside** [comment]
After a test, the implementation is wrong:

simple_bitmap_32bits bmp _fromrgba8

I guess the is a color reordering which is not done

**Comment by mtolly** [comment]
Agh, you're right. When I converted the test image I got this:
cover
And thought it looked correct (modulo transparency), but I neglected to check that the colors were in the right places. *But* my original image which was `(32, 1, 0)` is decoded correctly! The `3` mode must work differently -- I'll look into it and fix asap.

**Comment by Twinside** [comment]
I think it's simpler, I wouldn't be surprised that BMP stores RGBA as BGRA or ABGR (been there, done that :])

**Comment by mtolly** [comment]
Unfortunately it seems it's more complicated. A compression value of 0 (`BI_RGB`) is BGRA, which is what I implemented originally. A compression value of 3 (`BI_BITFIELDS`) means that after the `BITMAPINFOHEADER` there are four 32-bit masks (in the order red, green, blue, alpha) which basically specify a custom pixel format. The test image (which I made in GIMP) has:

```
  red 00 00 00 FF
green 00 00 FF 00
 blue 00 FF 00 00
alpha FF 00 00 00
```

so that means the pixels are ABGR order. Very odd stuff... I'll have a new PR shortly.

**Pull request merged**
