### PR TITLE
fixed some typos and errors in documentation. 

### PR DESCRIPTION
**Pull request by lehins**
Also added links to various DynamicImage constructors for encode/decode functions.

### CODE REVIEW

**Comment by Twinside** [comment]
Hi,

Thanks for the pull request,

I'd merge it when the regression on the bullet list are resolved. Haddock is a little touchy on this point, and there is a real need to have a blank line between items, otherwise they are rendered on the same line. I'm testing it with an haddock provided with GHC 7.6.3 (if it makes any difference).

Seen in:
  * src/Codec/Picture/Png.hs
  * src/Codec/Picture/Png/Export.hs
  * src/Codec/Picture/Tga.hs
  * src/Codec/Picture/Tiff.hs

I don't know why the documentation for `encodeDirectJpegAtQualityWithMetadata` is well rendered though.

**Comment by lehins** [comment]
I know previously it had some issues with lists. I've tested it with ghc 7.8.4 and Haddock 2.14.3. Everything seems to be well rendered. Here is a link to the documentation: https://lehins.com/html/JuicyPixels/

**Comment by lehins** [comment]
Just in case, I added new lines between bullet points. Hope it helps. Sorry, I cannot get it to render incorrectly, otherwise I'd fix it.

**Comment by Twinside** [comment]
I guess the Haddock from debian is really too old.

thanks again 🙂

**Pull request merged**
