### PR TITLE
Add Typeable instances

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Seems like the build timed-out

**Comment by Twinside** [comment]
I've restarted it

**Comment by phadej** [comment]
@Twinside I added a small script to make travis build go on, but I guess the whole build will still hit 60minutes limit with `-O3` on 7.10

**Comment by phadej** [comment]
To speedup the builds, could we change travis to build with `-O`, and not `-O3?. I'm quite sure, latter is not relevant for CI?

**Comment by Twinside** [comment]
Ok, I've made some tests, and I don't understand why TravisCI is taking so long, it built nearly instantly on my machine with GHC 7.10.3 (windows), and not 10 minutes to build just `Types.hs`. So I'm merging the patch and thanks for the Travis tweaking

**Pull request merged**
